version: "3.9"
services:
  api:
    image: ghcr.io/mixyboos/mixyboos-api
    ports:
      - "1935:1935"
      - "9091:9091"
    volumes:
      - ./data/mnt:/mnt/
      - /srv/dev/mixyboos/mixyboos-live/index.html:/mnt/index.html
      - /etc/letsencrypt/archive/dev.fergl.ie:/opt/ssl/
      - ./data/log:/var/log/nginx/
    container_name: mixyboos_rtmp
    extra_hosts:
      - "dev.mixyboos.com:10.1.1.1"
