version: "3.9"
services:
  api:
    image: ghcr.io/mixyboos/mixyboos-api
    restart: always
    networks:
      - "traefik_proxy"
    env_file:
      .env
    environment:
      ASPNETCORE_URLS: http://*:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mixyboos.rule=Host(`api.mixyboos.com`)"
      - "traefik.http.routers.mixyboos.entrypoints=websecure"
      - "traefik.http.routers.mixyboos.tls.certresolver=noodles-resolver"
networks:
  traefik_proxy:
    name: traefik_proxy
    external: true
