version: "3.9"
services:
  api:
    image: ghcr.io/mixyboos/mixyboos-api
    ports:
      - "80:80"
    restart: always
    networks:
      - "traefik_proxy"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kuma.rule=Host(`api.mixyboos.com`)"
      - "traefik.http.routers.kuma.entrypoints=websecure"
      - "traefik.http.routers.kuma.tls.certresolver=noodles-resolver"
      - "traefik.http.services.kuma.loadbalancer.server.port=80"
networks:
  traefik_proxy:
    name: traefik_proxy
    external: true
